### ISSUE TITLE
main_export_onnx.py

### ISSUE THREAD

**Issue by winterxx** [hpc203/yolov5-face-landmarks-opencv#3]
when run main_export_onnx.py , i get error:
Traceback (most recent call last):
  File "/media/xxx/data1/githubprj/face/yolov5-face/main_export_onnx.py", line 110, in <module>
    onnxmodel,img = test_export(opt)
  File "/media/xxx/data1/githubprj/face/yolov5-face/main_export_onnx.py", line 69, in test_export
    x = m(x)  # run
  File "/media/data1/3rdtool/anaconda3/envs/yolov5face/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/xxx/data1/githubprj/face/yolov5-face/models/common.py", line 227, in forward
    return torch.cat(x, self.d)
TypeError: expected Tensor as element 1 in argument 0, but got NoneType

**Comment by gouravvemula0** [comment]
same problem to me

**Comment by hpc203** [comment]
https://github.com/hpc203/yolov5-face-landmarks-opencv-v2
使用v2版本里的main_export_onnx.py
