### ISSUE TITLE
unable to convert to onnx

### ISSUE THREAD

**Issue by gouravvemula0** [hpc203/yolov5-face-landmarks-opencv#4]
Traceback (most recent call last):
File "/media/githubprj/face/yolov5-face/main_export_onnx.py", line 110, in
onnxmodel,img = test_export(opt)
File "/media/githubprj/face/yolov5-face/main_export_onnx.py", line 69, in test_export
x = m(x) # run
result = self.forward(*input, **kwargs)
File "/media/githubprj/face/yolov5-face/models/common.py", line 227, in forward
return torch.cat(x, self.d)
TypeError: expected Tensor as element 1 in argument 0, but got NoneType

I got the error while converting to onnx of the pretrained model yolov5n.pt

**Comment by qingqinghu1026** [comment]
碰到了同样的问题，有解决了的吗

**Comment by hpc203** [comment]
https://github.com/hpc203/yolov5-face-landmarks-opencv-v2
使用v2版本里的main_export_onnx.py
